#!/usr/bin/env bash
# Local license E2E: portal dev API on :9080 + WordPress mu-plugin constants.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOPLIST_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
PORTAL_ROOT="${PORTAL_ROOT:-$(realpath "${TOPLIST_ROOT}/../../portal" 2>/dev/null || true)}"
WP_ROOT="${WP_ROOT:-/var/www/html}"
PORTAL_PORT="${PORTAL_PORT:-9080}"
PORTAL_HOST="127.0.0.1"
API_URL="http://${PORTAL_HOST}:${PORTAL_PORT}/api/v1/toplist-block/validate"
PID_FILE="${TOPLIST_ROOT}/.local-portal-dev.pid"
LOG_FILE="${TOPLIST_ROOT}/.local-portal-dev.log"
MU_PLUGIN_TEMPLATE="${TOPLIST_ROOT}/dev/mu-plugins/toplist-local-license.php"
MU_PLUGIN_GENERATED="${TOPLIST_ROOT}/.local-toplist-license-mu.php"
MU_PLUGIN_DEST="${WP_ROOT}/wp-content/mu-plugins/toplist-local-license.php"

usage() {
  cat <<'EOF'
Usage: bash scripts/setup-local-license.sh [--no-server] [--domain DOMAIN]

Starts a PHP built-in server for the portal API (unless already listening),
installs a must-use plugin with TOPLIST_BLOCK_LICENSE_* constants, and issues
a dev lifetime license for the WordPress site domain.

Environment:
  PORTAL_ROOT   Path to portal checkout (default: ../portal sibling of Casino-project)
  WP_ROOT       WordPress root (default: /var/www/html)
  PORTAL_PORT   Portal API port (default: 9080)

Options:
  --no-server   Skip starting the portal dev server
  --domain      License domain (default: host from WP siteurl, else 127.0.0.1)
  -h, --help    Show this help
EOF
}

START_SERVER=1
LICENSE_DOMAIN=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --no-server) START_SERVER=0 ;;
    --domain) LICENSE_DOMAIN="${2:-}"; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 1 ;;
  esac
  shift
done

if [[ ! -d "${PORTAL_ROOT}" ]]; then
  echo "Portal repo not found at ${PORTAL_ROOT}. Set PORTAL_ROOT." >&2
  exit 1
fi

if [[ ! -f "${PORTAL_ROOT}/api/config.local.php" ]]; then
  echo "Missing ${PORTAL_ROOT}/api/config.local.php" >&2
  exit 1
fi

if [[ ! -f "${WP_ROOT}/wp-config.php" ]]; then
  echo "WordPress not found at ${WP_ROOT}." >&2
  exit 1
fi

API_KEY="$(
  php -r '
    $c = require $argv[1];
    echo isset($c["toplist_block_api_key"]) ? (string) $c["toplist_block_api_key"] : "";
  ' "${PORTAL_ROOT}/api/config.local.php"
)"
if [[ -z "${API_KEY}" ]]; then
  echo "toplist_block_api_key is not set in portal config.local.php" >&2
  exit 1
fi

portal_listening() {
  local code
  code="$(curl -s -o /dev/null -w '%{http_code}' -m 3 -X POST "${API_URL}" \
    -H 'Content-Type: application/json' \
    -H "Authorization: Bearer ${API_KEY}" \
    -d '{"domain":"127.0.0.1","license_key":"0000000000000000"}' || true)"
  [[ "${code}" =~ ^[0-9]+$ && "${code}" != "000" ]]
}

start_portal_server() {
  if portal_listening; then
    echo "Portal API already listening on ${API_URL}"
    return 0
  fi

  if [[ -f "${PID_FILE}" ]]; then
    old_pid="$(cat "${PID_FILE}" 2>/dev/null || true)"
    if [[ -n "${old_pid}" ]] && kill -0 "${old_pid}" 2>/dev/null; then
      echo "Stopping stale portal dev server (pid ${old_pid}) ..."
      kill "${old_pid}" 2>/dev/null || true
      sleep 1
    fi
    rm -f "${PID_FILE}"
  fi

  echo "Starting portal dev server on ${PORTAL_HOST}:${PORTAL_PORT} ..."
  (
    cd "${PORTAL_ROOT}"
    PORTAL_ROOT="${PORTAL_ROOT}" nohup php -S "${PORTAL_HOST}:${PORTAL_PORT}" \
      -t "${PORTAL_ROOT}" \
      "${TOPLIST_ROOT}/scripts/dev/portal-router.php" \
      >>"${LOG_FILE}" 2>&1 &
    echo $! >"${PID_FILE}"
  )

  for _ in $(seq 1 20); do
    if portal_listening; then
      echo "Portal API ready: ${API_URL}"
      return 0
    fi
    sleep 0.25
  done

  echo "Portal API did not become ready. See ${LOG_FILE}" >&2
  exit 1
}

install_mu_plugin() {
  cat >"${MU_PLUGIN_GENERATED}" <<PHP
<?php
/**
 * Plugin Name: Toplist Block Local License Config
 * Description: Dev-only license API constants (generated by scripts/setup-local-license.sh).
 */

if (!defined('TOPLIST_BLOCK_LICENSE_API_URL')) {
	define('TOPLIST_BLOCK_LICENSE_API_URL', '${API_URL}');
}
if (!defined('TOPLIST_BLOCK_LICENSE_API_KEY')) {
	define('TOPLIST_BLOCK_LICENSE_API_KEY', '${API_KEY}');
}
PHP

  local mu_dir
  mu_dir="$(dirname "${MU_PLUGIN_DEST}")"
  if [[ -w "${mu_dir}" ]] || { [[ ! -e "${mu_dir}" ]] && [[ -w "$(dirname "${mu_dir}")" ]]; }; then
    mkdir -p "${mu_dir}"
    cp "${MU_PLUGIN_GENERATED}" "${MU_PLUGIN_DEST}"
    if id www-data >/dev/null 2>&1; then
      chown www-data:www-data "${MU_PLUGIN_DEST}" 2>/dev/null || \
        sudo chown www-data:www-data "${MU_PLUGIN_DEST}" 2>/dev/null || true
    fi
  else
    echo "Installing mu-plugin with sudo ..."
    sudo mkdir -p "${mu_dir}"
    sudo cp "${MU_PLUGIN_GENERATED}" "${MU_PLUGIN_DEST}"
    if id www-data >/dev/null 2>&1; then
      sudo chown www-data:www-data "${MU_PLUGIN_DEST}"
    fi
  fi
  echo "Installed mu-plugin: ${MU_PLUGIN_DEST}"
}

resolve_license_domain() {
  if [[ -n "${LICENSE_DOMAIN}" ]]; then
    echo "${LICENSE_DOMAIN}"
    return 0
  fi
  if command -v wp >/dev/null 2>&1; then
    local url
    url="$(wp --path="${WP_ROOT}" option get siteurl 2>/dev/null || true)"
    if [[ -n "${url}" ]]; then
      php -r 'echo parse_url($argv[1], PHP_URL_HOST) ?: "";' "${url}"
      return 0
    fi
  fi
  echo "127.0.0.1"
}

if [[ "${START_SERVER}" -eq 1 ]]; then
  start_portal_server
else
  if ! portal_listening; then
    echo "Portal API is not reachable at ${API_URL}. Start it or omit --no-server." >&2
    exit 1
  fi
fi

install_mu_plugin

DOMAIN="$(resolve_license_domain)"
LICENSE_KEY="$(
  PORTAL_ROOT="${PORTAL_ROOT}" php "${TOPLIST_ROOT}/scripts/dev/issue-local-license.php" "${DOMAIN}"
)"

echo ""
echo "Dev license issued for domain: ${DOMAIN}"
echo "License key: ${LICENSE_KEY}"
echo ""
echo "Next steps:"
echo "  1. bash ../install-local.sh --plugin-only   # from Casino-project/"
echo "  2. Activate Toplist Block Pro in wp-admin"
echo "  3. Settings → Toplist Block → paste license → Save & verify"
echo ""
echo "Smoke test:"
echo "  curl -sS -X POST '${API_URL}' \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -H 'Authorization: Bearer ${API_KEY}' \\"
echo "    -d '{\"domain\":\"${DOMAIN}\",\"license_key\":\"${LICENSE_KEY}\"}'"
